apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-backend
  labels:
    app: fullstackapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstackapp-backend
  template:
    metadata:
      labels:
        app: fullstackapp-backend
    spec:
      containers:
        - name: back
          image: 09036229746/back:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - name: backport
              containerPort: 5000

---

kind: Service
apiVersion: v1
metadata:
  name: backservice
  labels:
    app: fullstackapp-backend
spec:
  selector:
    app: fullstackapp-backend
  type: NodePort
  ports:
    - port: 5000
      targetPort: backport
      protocol: TCP
