apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstackapp-frontend
  template:
    metadata:
      labels:
        app: fullstackapp-frontend
    spec:
      containers:
        - name: front
          image: 09036229746/front:v3
          resources:
            limits:
              memory: "120Mi"
              cpu: "250m"
          ports:
              - name: frontport
                containerPort: 3000
          env:
            - name: BACKEND_URL
              value: backservice

---

kind: Service
apiVersion: v1
metadata:
  name: frontservice
spec:
  selector:
    app: fullstackapp-frontend
  type: NodePort
  ports:
    - port: 3000
      targetPort: frontport
      protocol: TCP
